### PR TITLE
fix: update favorites and watch history lists when empty result

### PR DESCRIPTION
**Pull request by mirovladimitrovski**
## Description

This PR solves #PS-77.
https://jwplayer.atlassian.net/browse/PS-77

### Steps completed:

According to our definition of done, I have completed the following steps:

- [x] Acceptance criteria met
- [ ] Unit tests added
- [ ] Docs updated (including config and env variables)
- [ ] Translations added
- [ ] UX tested
- [x] Browsers / platforms tested
- [x] Rebased & ready to merge without conflicts
- [x] Reviewed own code

### CODE REVIEW

**Comment by ChristiaanScheermeijer** [comment]
I actually made the same changes yesterday in an upcoming refactor branch. It should be fine, though...

https://github.com/Videodock/ott-web-app/pull/37/files#diff-a08daab854bf0e61214fcae0e2ee7c11fddaa17b57fe8e714fae3fbe5fc3e4c5L48

https://github.com/Videodock/ott-web-app/pull/37/files#diff-7a5a56b9f122b14fcd7fd0c1ed20693bcedb9f2c060dbe56c6403d6bc12f2c67L58

**Comment by mirovladimitrovski** [comment]
> I actually made the same changes yesterday in an upcoming refactor branch. It should be fine, though...
> 
> https://github.com/Videodock/ott-web-app/pull/37/files#diff-a08daab854bf0e61214fcae0e2ee7c11fddaa17b57fe8e714fae3fbe5fc3e4c5L48
> 
> https://github.com/Videodock/ott-web-app/pull/37/files#diff-7a5a56b9f122b14fcd7fd0c1ed20693bcedb9f2c060dbe56c6403d6bc12f2c67L58

That's quite a big refactor. I think it'd be better to merge this fix first, so we can have it sooner.

**Review by budzworthy — APPROVED** [review]
Sorry this fell off the radar, but the changes look fine / simple. Would be nice to add an e2e test for this, but not mandatory if you don't have capacity.

**Comment by ChristiaanScheermeijer** [comment]
@dbudzins @mirovladimitrovski this PR is redundant because #450 was merged which already had this fix 😄

**Pull request closed without merging**
