### PR TITLE
chore: using staging instead of daily environment for useSandbox

### PR DESCRIPTION
**Pull request by darkoatanasovski**
## Description

Using staging environment instead of daily

This PR solves # .

### Steps completed:

According to our definition of done, I have completed the following steps:

- [ ] Acceptance criteria met
- [ ] Unit tests added
- [ ] Docs updated (including config and env variables)
- [ ] Translations added
- [ ] UX tested
- [ ] Browsers / platforms tested
- [ ] Rebased & ready to merge without conflicts
- [ ] Reviewed own code

### CODE REVIEW

**Comment by budzworthy** [comment]
@darkoatanasovski Will this update mean that the client and asset ID's in all of our test and demo configs need to be changed?

**Comment by darkoatanasovski** [comment]
@dbudzins yes 😐

**Comment by darkoatanasovski** [comment]
also, `app-preview.jwplayer.com` does not work with the latest code from develop branch(missing translation for `waiting for payment` modal, using `jwp` instead of `inplayer` property from the config).

**Comment by budzworthy** [comment]
> 

The property should now be jwp, not inplayer. A missing translation should be fixed, but won't kill the site.

Let's coordinate updating all the configs on the test property with the release of this and also make sure @marcovandeveen and company know (and let's do that all after hackweek unless this is a blocker for something?)

**Review by budzworthy — APPROVED** [review]

**Pull request merged**
